### ISSUE TITLE
Cannot Resolve References, IdSvr24 and IdSvr24EntityFramework

### ISSUE THREAD

**Issue by lenj962** [mustafasaaed/IdentityServerCommunityTemplatePack#4]
I downloaded and installed this package.  Added it to a project, but could not resolve the references in the title.  See attached screenshot.

![idsvr24-refs](https://user-images.githubusercontent.com/331374/32083501-9e463f1e-ba88-11e7-8b58-ad1dd4c6c7ab.jpg)

**Comment by mustafasaaed** [comment]
sorry for that . their is a bug in the template that change the name of those two packages when you change the project name, I am working on a fix but a workaround for now is to delete those packages and install the following packages :

- [Identity Server 4](https://www.nuget.org/packages/IdentityServer4/1.3.1)
- [Identity server 4 entity framework ](https://www.nuget.org/packages/IdentityServer4.EntityFramework/1.0.1)

Thank you for your feedback.

**Comment by lenj962** [comment]
Thanks.  I'll try this again.   I got the same errors.  There's a lot to swallow here.

**Comment by jbanks27** [comment]
the issue is a bit larger than that.  The template starts a project off as .NET core 2.0.  However, once you get past the incorrect Nuget references noted above and correct, you are then faced with a substantial amounts of rework with the type changes between 1.1 and 2.0

**Comment by mustafasaaed** [comment]
@jbanks27 at the time i made i created the template identity server did not support .net core 2.0 and i am   busy right now to update the template but i hope i will do that soon.

**Comment by mustafasaaed** [comment]
@lenj962  hi, I am very sorry for the late fix.Please try the extension again and feel free to reopen this issue.

**Comment by mustafasaaed** [comment]
@jbanks27 the template now supports .net core 2
